print("正在加载XU脚本...")
print("========================================")

--初始化变量local悬浮窗 = {}
local侧边栏 = {}
local当前样式 = "默认"
local正在移动 = falselocal触摸开始时间 =0local防误触时间 =300 --毫秒local已缩小 = falselocal原始大小 = {width=300, height=400}
local缩小大小 = {width=60, height=60}

--创建主悬浮窗function创建悬浮窗()
 --主窗口悬浮窗.窗口 = ui.newLayout("vertical", "fill,wrap")
悬浮窗.窗口:size(原始大小.width,原始大小.height)
悬浮窗.窗口:bg(0xFF222222)
悬浮窗.窗口:cornerRadius(15)
悬浮窗.窗口:shadow(0x80000000,5,0,3)
悬浮窗.窗口:position(50,100)
悬浮窗.窗口:freePosition(true)
 --标题栏 local标题栏 = ui.newLayout("horizontal", "fill")
标题栏:bg(0xFF333333)
标题栏:height(40)
标题栏:cornerRadius(15,15,0,0)
 --左上角移动区域（长按）
 local移动区域 = ui.newButton("")
移动区域:size(40,40)
移动区域:bg(0x00FFFFFF)
移动区域:onTouch(function(event)
 if event == "down" then触摸开始时间 = os.time()
正在移动 = false elseif event == "move" then if os.time() -触摸开始时间 >0.3 then正在移动 = true悬浮窗.窗口:freePosition(true)
 end elseif event == "up" then if正在移动 then正在移动 = false end end end)
 -- XU标志 local标志 = ui.newTextView("XU")
标志:textSize(20)
标志:textColor(0xFFFF00FF)
标志:textStyle("bold")
标志:marginLeft(10)
 --北京时间显示 local时间显示 = ui.newTextView("")
时间显示:textSize(14)
时间显示:textColor(0xFFFFFFFF)
时间显示:textStyle("bold")
 --更新时间函数 function更新时间()
 local当前时间 = os.date("%H:%M:%S")
时间显示:text("北京时间: " ..当前时间)
 end --关闭/缩小按钮 local关闭按钮 = ui.newButton("×")
关闭按钮:textSize(24)
关闭按钮:textColor(0xFFFF5555)
关闭按钮:size(40,40)
关闭按钮:onClick(function()
 if已缩小 then --恢复大小悬浮窗.窗口:size(原始大小.width,原始大小.height)
侧边栏.容器:show()
已缩小 = false else --缩小悬浮窗.窗口:size(缩小大小.width,缩小大小.height)
侧边栏.容器:hide()
已缩小 = true end end)
 --组装标题栏标题栏:addView(移动区域)
标题栏:addView(标志)
标题栏:addView(ui.newView(), "1") --弹性空间标题栏:addView(时间显示)
标题栏:addView(关闭按钮)
 --内容区域 local内容区域 = ui.newLayout("horizontal", "fill")
内容区域:weight(1)
 --创建侧边栏创建侧边栏()
 --主内容区 local主内容 = ui.newLayout("vertical", "fill")
主内容:bg(0xFF222222)
主内容:cornerRadius(0,0,15,0)
 --信息框 local信息框 = ui.newCardView()
信息框:cardBackgroundColor(0xFF2A2A2A)
信息框:cardCornerRadius(10)
信息框:cardElevation(5)
信息框:margin(10)
 local作者信息 = ui.newTextView("作者: HaoChen\nQQ:1626844714")
作者信息:textSize(16)
作者信息:textColor(0xFF00FFAA)
作者信息:padding(15)
作者信息:lineSpacing(8)
信息框:addView(作者信息)
 --样式预览区 local样式框 = ui.newCardView()
样式框:cardBackgroundColor(0xFF2A2A2A)
样式框:cardCornerRadius(10)
样式框:cardElevation(5)
样式框:margin(10,5,10,10)
 local样式标题 = ui.newTextView("当前样式: " ..当前样式)
样式标题:textSize(16)
样式标题:textColor(0xFFFFAA00)
样式标题:padding(15,15,5,5)
样式框:addView(样式标题)
 --组装主内容主内容:addView(信息框)
主内容:addView(样式框)
 --组装内容区域内容区域:addView(侧边栏.容器)
内容区域:addView(主内容)
 --组装主窗口悬浮窗.窗口:addView(标题栏)
悬浮窗.窗口:addView(内容区域)
 --启动时间更新 timer(1000,更新时间, true)
更新时间()
 --显示窗口悬浮窗.窗口:show()
 --加载动画 local加载动画 = ui.newProgressBar("horizontal")
加载动画:size(200,4)
加载动画:position(50,50)
加载动画:progressColor(0xFFFF00FF)
加载动画:show()
 --模拟加载 local进度 =0 timer(50, function()
进度 =进度 +5加载动画:progress(进度)
 if进度 >=100 then加载动画:hide()
 print("========================================")
 print("XU脚本加载完成！")
 print("========================================")
 return true --停止定时器 end end)
end--创建侧边栏function创建侧边栏()
侧边栏.容器 = ui.newLayout("vertical", "fill")
侧边栏.容器:width(80)
侧边栏.容器:bg(0xFF1A1A1A)
侧边栏.容器:cornerRadius(0,0,0,15)
 --信息按钮 local信息按钮 = ui.newButton("ℹ️\n信息")
信息按钮:textSize(12)
信息按钮:textColor(0xFFFFFFFF)
信息按钮:size(70,70)
信息按钮:margin(5,5,5,2)
信息按钮:cornerRadius(10)
信息按钮:bg(0xFF333333)
信息按钮:onClick(function()
切换侧边栏内容("信息")
 end)
 --样式按钮 local样式按钮 = ui.newButton("🎨\n样式")
样式按钮:textSize(12)
样式按钮:textColor(0xFFFFFFFF)
样式按钮:size(70,70)
样式按钮:margin(5,2,5,5)
样式按钮:cornerRadius(10)
样式按钮:bg(0xFF333333)
样式按钮:onClick(function()
切换侧边栏内容("样式")
 end)
侧边栏.容器:addView(信息按钮)
侧边栏.容器:addView(样式按钮)
end--切换侧边栏内容function切换侧边栏内容(类型)
 --这里可以扩展为实际的内容切换 print("切换到: " ..类型 .. "栏目")
end--样式切换函数function切换样式(样式名称)
当前样式 =样式名称 print("已切换到样式: " ..样式名称)
 --根据样式切换布局和颜色 if样式名称 == "科技蓝" then悬浮窗.窗口:bg(0xFF0A1A2A)
侧边栏.容器:bg(0xFF051222)
 elseif样式名称 == "暗夜紫" then悬浮窗.窗口:bg(0xFF1A0A2A)
侧边栏.容器:bg(0xFF120522)
 elseif样式名称 == "炫彩红" then悬浮窗.窗口:bg(0xFF2A0A0A)
侧边栏.容器:bg(0xFF220505)
 endend--创建样式选择界面function创建样式面板()
 local样式面板 = ui.newLayout("vertical", "wrap")
样式面板:size(250,300)
样式面板:bg(0xFF333333)
样式面板:cornerRadius(15)
样式面板:position(100,200)
样式面板:elevation(10)
 local标题 = ui.newTextView("选择样式")
标题:textSize(18)
标题:textColor(0xFFFF00FF)
标题:padding(15)
标题:textStyle("bold")
样式面板:addView(标题)
 --样式按钮 local样式列表 = {
 {"默认", "0xFF222222", "0xFF1A1A1A"},
 {"科技蓝", "0xFF0A1A2A", "0xFF051222"},
 {"暗夜紫", "0xFF1A0A2A", "0xFF120522"},
 {"炫彩红", "0xFF2A0A0A", "0xFF220505"}
 }
 for i,样式 in ipairs(样式列表) do local样式按钮 = ui.newButton(样式[1])
样式按钮:textSize(14)
样式按钮:textColor(0xFFFFFFFF)
样式按钮:height(50)
样式按钮:margin(10,5)
样式按钮:cornerRadius(10)
样式按钮:bg(tonumber(样式[2]))
样式按钮:onClick(function()
切换样式(样式[1])
样式面板:hide()
 end)
样式面板:addView(样式按钮)
 end --关闭按钮 local关闭按钮 = ui.newButton("关闭")
关闭按钮:textSize(14)
关闭按钮:textColor(0xFFFF5555)
关闭按钮:height(40)
关闭按钮:margin(10,5,10,10)
关闭按钮:cornerRadius(10)
关闭按钮:bg(0xFF444444)
关闭按钮:onClick(function()
样式面板:hide()
 end)
样式面板:addView(关闭按钮)
样式面板:hide()
 return样式面板end--初始化function main()
创建悬浮窗()
 --创建样式面板 local样式面板 =创建样式面板()
 --添加样式切换按钮到主界面 local样式切换按钮 = ui.newButton("切换样式")
样式切换按钮:textSize(14)
样式切换按钮:textColor(0xFFFFAA00)
样式切换按钮:height(40)
样式切换按钮:margin(10)
样式切换按钮:cornerRadius(10)
样式切换按钮:bg(0xFF333333)
样式切换按钮:onClick(function()
 if样式面板:isShowing() then样式面板:hide()
 else样式面板:show()
 end end)
 --将按钮添加到样式框 local样式框 =悬浮窗.窗口:getChildAt(1):getChildAt(1):getChildAt(1)
样式框:addView(样式切换按钮)
end--启动脚本main()